// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ml7vf13-NeDFHLinytqhQM8LpFK2Cbw',
    appId: '1:1071314257177:android:48cc53568dcf72aef3f188',
    messagingSenderId: '1071314257177',
    projectId: 'shop-30f59',
    databaseURL: 'https://shop-30f59-default-rtdb.firebaseio.com',
    storageBucket: 'shop-30f59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX3d6UejYgmAXKtrlHx_sQNes9UuL-wQY',
    appId: '1:1071314257177:ios:b9ddbf4c6166f42bf3f188',
    messagingSenderId: '1071314257177',
    projectId: 'shop-30f59',
    databaseURL: 'https://shop-30f59-default-rtdb.firebaseio.com',
    storageBucket: 'shop-30f59.appspot.com',
    androidClientId: '1071314257177-svsflghefgb02a50uoqsnmvi800qpn4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bayoumStoreApp',
  );
}
